In [6]:
# map with lambda
nums = [1, 2, 3, 4, 5]

mylist = list(map(lambda n: n * 2, nums))

print(mylist)

[2, 4, 6, 8, 10]


In [7]:
# map with def
def double(n):
    return n * 2

nums = [1, 2, 3, 4, 5, 6]
list(map(double, nums))

[2, 4, 6, 8, 10, 12]

In [8]:
# filter
nums = [1, 2, 3, 4, 5]

list(filter(lambda n: n % 2 == 1, nums))

[1, 3, 5]

In [11]:
# multiple iterables
list_0 = [1, 2, 3, 4] # to fill x
list_1 = [10, 20, 30, 40] # to fill y
print(list(map(lambda x, y: x * y, list_0, list_1)))


[10, 40, 90, 160]


In [15]:
# list comprehensions and generator expressions

l = [-2, -1, 0]
absolute_values = [abs(x) for x in l]
print(absolute_values)

squared_values = [x**2 for x in l]
print(squared_values)

list_0 = [1, 2, 3, 4] # to fill x
list_1 = [10, 20, 30, 40] # to fill y
multiply_results = [x * y for x, y in zip(list_0, list_1)]
print(multiply_results)


[2, 1, 0]
[4, 1, 0]
[10, 40, 90, 160]


In [16]:
# NumPy
import numpy as np

a = np.array([-2, -1, 0])
print(np.abs(a))
# [2 1 0]

print(a**2)
# [4 1 0]

a_1 = np.array([1, 2, 3])
a_2 = np.array([10, 20, 30])
print(a_1 * a_2)
# [10 40 90]

[2 1 0]
[4 1 0]
[10 40 90]
